[project]
name = "edu-press"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.3",
    "django-schema-viewer>=0.5.3",
    "drf-spectacular[sidecar]>=0.28.0",
]
